classes:

  - name: Body Massage
    hanyu: 按摩
    descripcion: |
      We offer a wide range of massage options
      to help clients achieve optimal health and wellness.
      Our experienced therapists are trained in a variety of techniques
      such as Tui-Na, Swedish massage, deep tissue massage, sports massage, and prenatal massage.
      Complementary hot stones upon request.
      Our therapists will work with you to create a personalized treatment plan
      that addresses your specific goals and needs.
    services:
      - name: 30Min Massage
        duracion: 30 minutes @ $50.00
        schedule_key: 39928472
      - name: 60min Massage
        duracion: 1 hour @ $80.00
        schedule_key: 39923045
      - name: 90min Massage
        duracion: 1 hour 30 minutes @ $120.00
        schedule_key: 39925969
      - name: 2hrs Massage
        duracion: 2 hours @ $160.00
        schedule_key: 43792772

  - name: Reflexology with Chinese Medicine
    hanyu: 脚部按摩
    descripcion: |
      This technique involves the application of Chinese Medicine and physical pressure
      to sprecific pressure point areas located on the feet or the hands.
      These pressure points are believed to correspond
      to various organs and systems of the body.
      It is used in order to bring relaxation and healing
      to the corresponding areas of the body
      as well as assist with stress relief.
    services:
      - name: 30Min Reflexology with Chinese Medicine
        duracion: 30 minutes @ $50.00
        schedule_key: 39928923
      - name: 60Min Reflexology with Chinese Medicine
        duracion: 1 hour @ $80.00
        schedule_key: 39928967
      - name: 90Min Reflexology with Chinese Medicine
        duracion: 1 hour 30 minutes @ $120.00
        schedule_key: 39929015

  - name: Cupping
    hanyu: 拔罐
    descripcion: |
      Cupping is a traditional Chinese therapy involving using suction cups
      to create a vacuum on the skin.
      This suction helps to stimulate circulation,
      loosen tight muscles, and improve overall well-being.
      Cupping can be used to address a variety of conditions,
      including muscle soreness, stiffness, and inflammation.
      Our therapists are trained in the proper technique and use of cupping
      to ensure that you receive the best possible care.
    services:
      - name: Cupping
        hanyu: 拔罐
        duracion: 20 minutes @ $40.00
        schedule_key: 39928578
      - name: Moving Cupping
        hanyu: 走罐
        duracion: 30 minutes @ $60.00
        schedule_key: 39928780
        descripcion: |
          Moving cupping is a type of cupping therapy that involves the use of
          small cups that are moved over the skin to create suction and improve
          circulation. This technique is believed to help improve muscle
          function and reduce pain and stiffness.
      - name: Wet Cupping
        hanyu: 刺血拔罐
        duracion: 10 minutes @ $45.00
        schedule_key: 39931669
        descripcion: |
          This technique is similar to the “cupping” method,
          however with this technique your skin is punctured slightly,
          and blood is drawn out during the suction process.
          This is thus used to improve both lymphatic and blood circulation
          and relieve pain.
          NOTE: this only is applied on a single accupuncture point.

  - name: Other Traditional Therapies & Specialty Treatments
    services:
      - name: Moxibustion
        hanyu: 艾灸
        duracion: 30 minutes @ $60.00
        schedule_key: 39928656
        descripcion: |
          Traditional Moxibustion is a therapeutic practice deeply rooted in
          Chinese medicine. It involves the controlled burning of dried Chinese
          mugwort (Artemisia vulgaris) on specific points or areas of the body
          to stimulate healing and promote overall well-being.
          At Pain Away of Philly, our therapists are trained
          in the proper use of moxibustion and will work with you
          to determine if it is a suitable treatment option for your needs.

      - name: Gua Sha
        hanyu: 刮痧
        duracion: 30 minutes @ $60.00
        schedule_key: 39928881
        descripcion: |
          Gua sha massage is a technique that involves scraping the skin
          with a special massage tool to improve circulation and reduce inflammation.
          This process, also known as coining, spooning, or scraping.

          In addition to promoting healing and improving circulation,
          it releases the blocked energy and heat, decrease inflammation,
          relieve pain, tension, detoxify, nourish the skin, cell nourishment
          and strengthens the immunes system. and effectively reducing
          hypertension.

      - name: Foot Shaping / Pedicure Therapy
        hanyu: 修脚
        duracion: 15 minutes @ $40.00
        schedule_key: 53993217
        descripcion: |
          Cosmetic treatment of the feet and toenails. During the treatment,
          dead skin cells are scraped off and toenails will be properly trimmed
          and cleaned.

      - name: Ear Cleansing Therapy
        hanyu: 采耳
        duracion: 15 minutes @ $40.00
        schedule_key: 53993230
        descripcion: |
          Ear cleansing therapy offers a tranquil blend of calm, relief, and
          sheer relaxation. It helps with ear congestion, ear-ache, and
          prevents infection.

      - name: Maternal Massage
        hanyu: 产妇按摩
        duracion: 45 minutes @ $90.00
        schedule_key: 53993252
        descripcion: |
          Our maternal massage is tailored to support expecting and new
          mothers, aiding in both pregnancy comfort and postnatal recovery.
          This specialized massage not only eases pregnancy discomfort but also
          addresses lactation pain, providing nurturing care during this
          transformative time in a woman's life

      - name: Thermo-Therapy
        hanyu: 中药热敷
        duracion: 45 minutes @ $35.00
        schedule_key: 39929598
        descripcion: |
          Chinese medicine is applied
          to the acupuncture points on the body surface and then heated.
          The combination of Chinese medicine and hot compresses
          allows the medicine to be locally absorbed through the skin,
          reaching lesions and making the treatment more direct and effective.
          NOTE: This booking is per body part (ei. lower back, upper back etc)

  - name: Combo Package
    services:
      - name: Scalp massage w. Gua-Sha Therapy
        hanyu: 头皮按摩 + 刮痧
        duracion: 30 minutes @ $60.00
        schedule_key: 53993063
        descripcion: |
          A harmonious blend of relaxation and rejuvenation. Feel tension melt
          away with a scalp massage, and let Gua-sha therapy leave you with a
          radiant glow

      - name: Facial Massage w. Gua-sha and Moxibustion
        hanyu: 面部按摩 + 刮痧 + 艾灸
        duracion: 45 minutes @ $80.00
        schedule_key: 53993130
        descripcion: |
          Ultimate wellness trio - a combination of scalp massage, Gua-Sha
          therapy, and Moxibustion. Relive tension with a soothing scalp
          massage, achieve a radiant glow with Gua-Sha, and experience the
          therapeutic benefits of Moxibustion for complete relaxation and
          rejuvenation.

      - name: Abdominal massage w. Moxibustion
        hanyu: 腹部按摩 + 艾灸
        duracion: 30 minutes @ $60.00
        schedule_key: 53993179
        descripcion: |
          Perfect balance of relaxation and holistic well-being with our
          abdominal massage and moxibustion combo.
